version: "3.1"

#volumes:
#    mongodb: ~

services:

    mongodb:
        image: mongo
        #image: mongo:3.6
        hostname: mongodb
        container_name: db-mongo
        #expose:
        #    - "27017"
        ports:
            - "27017:27017"
        #command: --bind_ip_all --smallfiles --nojournal
        #command: --bind_ip_all --smallfiles # "smallfiles" removed in mongo 4.2
        command: --bind_ip_all # for latest mongo 4.2
        # WARNING: Dokcer volumes on Windows and OS X is not compatible with MongoDB
        #volumes:
            #- mongodb:/data
            #- H:/Work/Git/vbx_fiware_comps/mdb_storage:/data
            #- H:/Work/Git/vbx_fiware_comps/mdb_storage:/data/db


    orion:
        image: fiware/orion
        #image: fiware/orion:2.3.0
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongodb
        #links: 
        #    - mongodb
        #expose:
        #    - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb


    iot-agent:
        image: fiware/iotagent-json
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongodb
        #expose:
        #    - "4041"
        #    - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_MONGO_HOST=mongodb"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-json"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent:4041"
            # added by RTG
            - "IOTA_LOG_LEVEL=DEBUG"


    draco:
        image: ging/fiware-draco
        container_name: draco
        depends_on:
            - mongodb
        environment:
            - NIFI_WEB_HTTP_PORT=9090
        expose:
            - "5050"
        ports:
            - "9090:9090"
            - "5050:5050"
            
