FROM raspbian/jessie


# CONFIG

ENV ROOT_DIR=/var/fiware
ENV TEMP_DIR=${ROOT_DIR}/temp/

ENV OPENSSL_VER=openssl-1.1.1g
ENV OPENSSL_ZIP=${OPENSSL_VER}.tar.gz
ENV OPENSSL_URL=https://www.openssl.org/source/${OPENSSL_ZIP}
ENV OPENSSL_SRC=${TEMP_DIR}/${OPENSSL_VER}-src
ENV OPENSSL_DIR=${ROOT_DIR}/${OPENSSL_VER}-portable

ENV PYTHON_VER=Python-3.8.2
ENV PYTHON_ZIP=${PYTHON_VER}.tgz
ENV PYTHON_URL=https://www.python.org/ftp/python/3.8.2/${PYTHON_ZIP}
ENV PYTHON_SRC=${TEMP_DIR}/${PYTHON_VER}-src
ENV PYTHON_DIR=${ROOT_DIR}/${PYTHON_VER}-portable


# Prepare working dirs

RUN mkdir ${ROOT_DIR} && chmod 777 ${ROOT_DIR}
RUN mkdir ${TEMP_DIR} && chmod 777 ${TEMP_DIR}
RUN mkdir ${OPENSSL_SRC} && chmod 777 ${OPENSSL_SRC}
RUN mkdir ${OPENSSL_DIR} && chmod 777 ${OPENSSL_DIR}
RUN mkdir ${PYTHON_SRC} && chmod 777 ${PYTHON_SRC}
RUN mkdir ${PYTHON_DIR} && chmod 777 ${PYTHON_DIR}


# Install C/C++ compiler environment

RUN apt-get update && apt upgrade -y 
RUN apt-get install --reinstall build-essential -y
RUN apt-get install --reinstall gcc -y
RUN dpkg-reconfigure build-essential
RUN dpkg-reconfigure gcc
RUN apt-get install libffi-dev -y
RUN apt-get install zlib1g-dev -y
RUN apt-get install libbz2-dev -y
RUN apt-get autoremove -y && apt-get clean -y


# Download, build and inslall (portable) OpenSSL

RUN cd ${TEMP_DIR} && \
    wget ${OPENSSL_URL} && \
    tar xavf ./${OPENSSL_ZIP} -C ${OPENSSL_SRC}
    
RUN cd ${OPENSSL_SRC}/${OPENSSL_VER} && \
    ./config shared CFLAGS=-fPIC --prefix=${OPENSSL_DIR} --openssldir=${OPENSSL_DIR}

RUN cd ${OPENSSL_SRC}/${OPENSSL_VER} && \
    make
    
RUN cd ${OPENSSL_SRC}/${OPENSSL_VER} && \
    make install


# Download, build and inslall (portable) Python3

RUN cd ${TEMP_DIR} && \ 
    wget ${PYTHON_URL} && \ 
    tar xavf ./${PYTHON_ZIP} -C ${PYTHON_SRC}
    
ENV LD_LIBRARY_PATH=${PYTHON_DIR}/lib:${OPENSSL_DIR}/lib:${LD_LIBRARY_PATH}

RUN cd ${PYTHON_SRC}/${PYTHON_VER} && \ 
    ./configure CFLAGS="-I${OPENSSL_DIR}/include" LDFLAGS="-L${OPENSSL_DIR}/lib -Wl,-rpath=${PYTHON_DIR}/lib" --enable-optimizations --enable-shared --prefix=${PYTHON_DIR} --with-openssl=${OPENSSL_DIR}

RUN cd ${PYTHON_SRC}/${PYTHON_VER} && \ 
    make

RUN cd ${PYTHON_SRC}/${PYTHON_VER} && \ 
    make install


# Install additional Python3 modules

RUN ${PYTHON_DIR}/bin/python3 -m pip install --upgrade pip

RUN ${PYTHON_DIR}/bin/python3 -m pip install --upgrade wheel setuptools pyinstaller

RUN ${PYTHON_DIR}/bin/python3 -m pip install --ignore-installed requests

RUN ${PYTHON_DIR}/bin/python3 -m pip install --ignore-installed aiohttp aiohttp_cors


# Compile vbox fiware connector to onefile-executable for raspbian

CMD ["/bin/sh", "-c", \
     "cd ./var/fiware/temp/ && ./../Python-3.8.2-portable/bin/python3 -u -m PyInstaller ./vbox_fiware_connector.py -F" ]
